In [8]:
import pandas as pd
from mod06_deanonymize import load_data, link_records, deanonymization_rate

In [9]:
anon_path = "mod06_data/anonymized.csv"
aux_path = "mod06_data/auxiliary.csv"

### Load and review the data

In [10]:
anon, aux = load_data(anon_path, aux_path)

In [11]:
anon.head(20)

   anon_id  age  zip3 gender
0    ERM5C   50   432      F
1    OFJJP   75   323      F
2    I3H24   44   323      M
3    3WUYW   66   323      M
4    ZN91P   18   323      M
5    7BLKV   36   606      F
6    4SJFH   70   890      M
7    0NO3L   31   110      M
8    U060Z   80   191      F
9    1761H   58   606      M
10   I9UI2   53   432      M
11   OO0ZT   47   941      F
12   BPEI7   19   112      M
13   ULMOZ   47   110      M
14   ES0E7   75   323      F
15   XCR1D   73   606      M
16   AY6JA   69   323      M
17   Q1J6V   40   941      F
18   BU6DU   54    62      F
19   LL1K7   69    21      M

In [12]:
#Checking to see if there are any repeat ids (age, zip3, gender)
mask = anon.duplicated(subset=["age", "zip3", "gender"], keep=False)
checking_for_dupes = anon[mask]
checking_for_dupes[checking_for_dupes["age"] == 75]
#Essentially what this shows is that there are certain ids with the same age zip3 & gender


#Take case of OFJIP & ES0E7
#if there is only one person in the auxillary list that matches combo (age, zip3, gender)
#It will merge across both of them anon_ids. Causing a duplicate in names
#if there is more then one then we will have a duplicate on anon_ids anyway
#and if there are none then it wouldn't be merged anyway.

#SO KEY TAKEAWAY:
#We need to filter for duplicates for both anon_id AND matched_name
#to garuntee only unique matches.

    anon_id  age  zip3 gender
1     OFJJP   75   323      F
14    ES0E7   75   323      F
222   HJGRB   75   191      M
493   O6KRG   75   606      M
520   Q2Y0G   75   191      M
698   FIBWF   75   606      M
811   PP06B   75   606      M

### Merge the datasets by age, gender, and zip3 and return the unique matches

In [13]:
matches = link_records(anon, aux)
matches

     anon_id    matched_name
7      ZN91P   Kyle Martinez
32     LL1K7    Omar Jackson
76     8J8S0       Alice Lee
95     T9W97   Viola Jackson
160    D4J2J    Julia Garcia
177    HATWJ     Grace Moore
329    Q6K3L   Hannah Taylor
381    GZN5L      Paul Patel
421    S6JRW   Paul Gonzalez
422    RSMO2      Lisa Patel
428    VEMQL    Carol Nguyen
500    71G60     Omar Taylor
520    P7V0N  Nancy Gonzalez
658    W8F8W    Frank Martin
683    UJ9WQ     Paul Wilson
711    NHFZR     Ivan Garcia
776    VV14D     Kyle Wilson
853    4NN94    Nancy Nguyen
894    88Y3M    David Garcia
920    99C9D   Marcus Nguyen
933    FW4EQ       Viola Lee
979    DSEW2    Lisa Johnson
981    D4N7I     Omar Garcia
1038   1G9JD     Julia Jones
1248   EUG9M    Viola Taylor
1249   RG7KC    Frank Taylor
1351   IDFZB      Omar Smith
1365   YMEK3    David Martin
1426   VYX2R      Paul Davis
1499   WUXQR      Emma Lopez
1518   VZ84N    David Wilson
1557   3PUZK  David Gonzalez
1590   2HE3C    Alice Wilson
1644   JO0TJ      Lisa Jones
1815   7FX6K   Alice Jackson
1857   E9JD1     Carol Brown
1866   MFDIB  Viola Gonzalez
1936   5VJDV   Viola Johnson

### Calculate the match rate

In [14]:
rate = deanonymization_rate(matches, anon)
print(rate)

0.038

# Discussion Questions

### Describe your reaction to the match rate. What sources of data might be prone to privacy issues?

My match rate was 0.38, a shockingly high number given the barriers in place. This 0.38 is only unique one to one matches. If we instead extended this to, say, a gropu of potential canidates for each anon_id, we could get a match rate of 1.0 (I tested this). Meaning for every row in the anon ID there is at least one row in the auxillary list that has matching credentials, some just have multiple. It's a little scary thinking about the implications of how much you could narrow down any row in an anonymized data set to just a couple people.

Any data, or combination of data, that can be cross referenced with public records & serve as a primary key seems like it would be extremely effective at finding one to one matches. Locational and Birth Information I feel are especially prone, as if you have someones address you can easily look up there name, where they work, etc. So things like: Address info (even partial), Birthday/year, or Even Marriage status, could eventually lead to security issues

### Provide examples of at least two other variables that could increase the match rate if included.

Lots of things could be added: Birth Month, Marriage Status, Income Level, Presence of Criminal History (T or F), or even something as small as just turning zip3 into zip4 could go a long way increasing the match rate. The biggest problem with the match rate currently is that for a lot a rows the features could be applied to multiple people. So by adding more features or a feature with more possible options, this should become less and less of an issue.